services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:16'
    env_file:
      - 'dashgreen/.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  app:
    build:
      context: dashgreen/.
      dockerfile: Dockerfile
    restart: always
    container_name: app
    # depends_on:
    #   - api
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Sao_Paulo  # Defina o timezone aqui
    volumes:
      - ./dashgreen:/app  # Monta o diretório local dentro do container
  
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"  # Porta para acessar o painel de controle do Nginx Proxy Manager
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

volumes:
  postgres:
  pgadmin_data: