# Generated by Django 5.1.1 on 2024-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
