"""Adiciona campo total na tabela Transacao

Revision ID: c8f66357db19
Revises: cbcf40a4024e
Create Date: 2024-09-30 10:28:31.875275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f66357db19'
down_revision: Union[str, None] = 'cbcf40a4024e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacao', 'total')
    # ### end Alembic commands ###
