"""Adiciona campo odd na tabela Transacao

Revision ID: cbcf40a4024e
Revises: e0bd12edbfd3
Create Date: 2024-09-30 10:25:53.925065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcf40a4024e'
down_revision: Union[str, None] = 'e0bd12edbfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('odd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacao', 'odd')
    # ### end Alembic commands ###
