"""update_trasacoes

Revision ID: d8c288257f51
Revises: c8f66357db19
Create Date: 2024-10-02 08:38:27.781237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c288257f51'
down_revision: Union[str, None] = 'c8f66357db19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('data_transacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacao', 'data_transacao')
    # ### end Alembic commands ###
