"""Validar usuario_id na criação de mercado

Revision ID: e0bd12edbfd3
Revises: e0a0ad4d7b4e
Create Date: 2024-09-19 14:49:13.471651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bd12edbfd3'
down_revision: Union[str, None] = 'e0a0ad4d7b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
