# Generated by Django 5.1.1 on 2024-10-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
